import React, { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Palette, Radius, Spacing, FontSize, FontWeight } from '@/constants/theme';
import { useAuraStore } from '@/stores/auraStore';
const choices = ['Casual', 'Smart casual', 'Minimal', 'Classic', 'Streetwear', 'Traditional'];
export default function Onboarding() { const [selected, setSelected] = useState<string[]>([]); const complete = useAuraStore((s) => s.completeOnboarding); const toggle=(choice:string)=>setSelected((all)=>all.includes(choice)?all.filter((value)=>value!==choice):[...all,choice]); return <SafeAreaView style={styles.container}><View style={styles.content}><Text style={styles.kicker}>YOUR STYLE</Text><Text style={styles.title}>What feels most like you?</Text><Text style={styles.copy}>Choose a few starting points. Aura will learn from every look you react to.</Text><View style={styles.choices}>{choices.map((choice)=><TouchableOpacity key={choice} onPress={()=>toggle(choice)} style={[styles.choice,selected.includes(choice)&&styles.selected]}><Text style={[styles.choiceText,selected.includes(choice)&&styles.selectedText]}>{choice}</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.button} onPress={()=>{complete({styleKeywords:selected,commonOccasions:['casual'],preferredColors:[]});router.replace('/(tabs)');}}><Text style={styles.buttonText}>Start my wardrobe</Text></TouchableOpacity></View></SafeAreaView>; }
const styles=StyleSheet.create({container:{flex:1,backgroundColor:Palette.black},content:{flex:1,justifyContent:'center',padding:Spacing[6]},kicker:{color:Palette.accent,fontSize:FontSize.sm,fontWeight:FontWeight.bold,letterSpacing:2,marginBottom:Spacing[3]},title:{color:Palette.textPrimary,fontSize:FontSize['3xl'],fontWeight:FontWeight.bold,letterSpacing:-1},copy:{color:Palette.textSecondary,fontSize:FontSize.md,lineHeight:25,marginTop:Spacing[3],marginBottom:Spacing[6]},choices:{flexDirection:'row',flexWrap:'wrap',gap:Spacing[2]},choice:{borderColor:Palette.glassBorder,borderWidth:1,borderRadius:Radius.full,paddingHorizontal:Spacing[4],paddingVertical:Spacing[3],backgroundColor:Palette.surface1},selected:{backgroundColor:Palette.accent,borderColor:Palette.accent},choiceText:{color:Palette.textSecondary,fontSize:FontSize.base},selectedText:{color:Palette.white,fontWeight:FontWeight.semiBold},button:{backgroundColor:Palette.accent,borderRadius:Radius.full,padding:Spacing[4],alignItems:'center',marginTop:Spacing[8]},buttonText:{color:Palette.white,fontWeight:FontWeight.semiBold,fontSize:FontSize.base}});
