import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Palette, Radius, Spacing, FontSize, FontWeight } from '@/constants/theme';
import { ScreenHeader } from '@/components/shared/ScreenHeader';
import { EmptyState } from '@/components/shared/EmptyState';
import { useAuraStore } from '@/stores/auraStore';
import { generateOutfit } from '@/services/outfits/generate';

export default function HomeScreen(){ const { user, wardrobe, outfits, addOutfit }=useAuraStore(); const generate=()=>{if(!user)return;const outfit=generateOutfit(user.id,wardrobe);if(outfit){addOutfit(outfit);router.push('/(tabs)/style');}}; return <SafeAreaView style={styles.container} edges={['top']}><ScreenHeader title="AURA" subtitle="Your wardrobe, in harmony" showAvatar onAvatarPress={()=>router.push('/(tabs)/profile')}/><ScrollView contentContainerStyle={styles.content}>{wardrobe.length<2?<EmptyState icon="✦" title="Your first look starts here" description="Add a top and a bottom (or a dress), then Aura can build looks from your own wardrobe." actionLabel="Add clothing" onAction={()=>router.push('/(tabs)/create')}/>:<View><View style={styles.hero}><Text style={styles.eyebrow}>TODAY’S LOOK</Text><Text style={styles.headline}>Dress from what{`\n`}you already love.</Text><Text style={styles.copy}>{wardrobe.length} items in your private wardrobe</Text><TouchableOpacity style={styles.button} onPress={generate}><Text style={styles.buttonText}>Generate an outfit</Text></TouchableOpacity></View>{outfits[0]&&<View style={styles.summary}><Text style={styles.summaryTitle}>Latest Aura look</Text><Text style={styles.summaryCopy}>{outfits[0].slots.length} pieces selected from your wardrobe</Text></View>}</View>}</ScrollView></SafeAreaView>; }
const styles=StyleSheet.create({container:{flex:1,backgroundColor:Palette.black},content:{flexGrow:1,paddingHorizontal:Spacing[5],paddingBottom:120},hero:{marginTop:Spacing[5],padding:Spacing[6],borderRadius:Radius.xl,backgroundColor:Palette.surface1,borderWidth:1,borderColor:Palette.glassBorder},eyebrow:{color:Palette.rose,fontSize:FontSize.xs,fontWeight:FontWeight.bold,letterSpacing:1.5},headline:{color:Palette.textPrimary,fontSize:FontSize['2xl'],fontWeight:FontWeight.bold,letterSpacing:-.6,marginTop:Spacing[3]},copy:{color:Palette.textSecondary,fontSize:FontSize.sm,marginTop:Spacing[3]},button:{alignSelf:'flex-start',backgroundColor:Palette.accent,borderRadius:Radius.full,paddingHorizontal:Spacing[5],paddingVertical:Spacing[3],marginTop:Spacing[6]},buttonText:{color:Palette.white,fontWeight:FontWeight.semiBold},summary:{marginTop:Spacing[4],padding:Spacing[4],borderRadius:Radius.md,backgroundColor:Palette.surface1},summaryTitle:{color:Palette.textPrimary,fontWeight:FontWeight.semiBold},summaryCopy:{color:Palette.textSecondary,fontSize:FontSize.sm,marginTop:4}});
