import React, { useMemo, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Palette, Radius, Spacing, FontSize, FontWeight } from '@/constants/theme';
import { ScreenHeader } from '@/components/shared/ScreenHeader';
import { EmptyState } from '@/components/shared/EmptyState';
import { useAuraStore } from '@/stores/auraStore';

export default function WardrobeScreen() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All');
  const wardrobe = useAuraStore((s) => s.wardrobe);
  const items = useMemo(() => wardrobe.filter((item) => (category === 'All' || item.category === category) && `${item.name} ${item.primaryColor} ${item.subcategory}`.toLowerCase().includes(query.toLowerCase())), [wardrobe, query, category]);
  const categories = ['All', ...new Set(wardrobe.map((item) => item.category))];
  return <SafeAreaView style={styles.container} edges={['top']}><ScreenHeader title="Wardrobe" /><View style={styles.body}><TextInput value={query} onChangeText={setQuery} placeholder="Search your wardrobe" placeholderTextColor={Palette.textTertiary} style={styles.search}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{categories.map((value) => <Pressable key={value} onPress={() => setCategory(value)} style={[styles.filter, category === value && styles.filterActive]}><Text style={[styles.filterText, category === value && styles.filterTextActive]}>{value}</Text></Pressable>)}</ScrollView>{items.length === 0 ? <EmptyState icon="👗" title={wardrobe.length ? 'No matching items' : 'Your wardrobe is empty'} description="Photograph your clothing and Aura will recognise and catalogue it for you." actionLabel="Add first item" onAction={() => router.push('/(tabs)/create')}/> : <ScrollView contentContainerStyle={styles.grid}>{items.map((item) => <Pressable key={item.id} style={styles.card} onPress={() => router.push(`/item/${item.id}`)}><Image source={{ uri: item.thumbnailUrl }} style={styles.image}/><Text numberOfLines={1} style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.primaryColor} · {item.category}</Text></Pressable>)}</ScrollView>}</View></SafeAreaView>;
}
const styles = StyleSheet.create({ container:{flex:1,backgroundColor:Palette.black},body:{flex:1,paddingHorizontal:Spacing[5]},search:{backgroundColor:Palette.surface1,borderColor:Palette.glassBorder,borderWidth:1,borderRadius:Radius.md,color:Palette.textPrimary,padding:Spacing[3],fontSize:FontSize.base},filters:{gap:Spacing[2],paddingVertical:Spacing[3]},filter:{paddingHorizontal:Spacing[3],paddingVertical:Spacing[2],borderRadius:Radius.full,backgroundColor:Palette.surface1},filterActive:{backgroundColor:Palette.accent},filterText:{color:Palette.textSecondary,textTransform:'capitalize',fontSize:FontSize.sm},filterTextActive:{color:Palette.white,fontWeight:FontWeight.semiBold},grid:{flexDirection:'row',flexWrap:'wrap',gap:Spacing[3],paddingBottom:120},card:{width:'47%',backgroundColor:Palette.surface1,borderRadius:Radius.md,overflow:'hidden',paddingBottom:Spacing[3]},image:{width:'100%',aspectRatio:.86,backgroundColor:Palette.surface2},name:{color:Palette.textPrimary,fontSize:FontSize.base,fontWeight:FontWeight.semiBold,paddingHorizontal:Spacing[3],paddingTop:Spacing[3],textTransform:'capitalize'},meta:{color:Palette.textSecondary,fontSize:FontSize.xs,paddingHorizontal:Spacing[3],paddingTop:2,textTransform:'capitalize'} });
